print("--- CHẠY BÀI 4 ---")
s = input("Nhập vào một chuỗi bất kỳ: ")
hoa = sum(1 for c in s if c.isupper())
thuong = sum(1 for c in s if c.islower())
so = sum(1 for c in s if c.isdigit())
trang = sum(1 for c in s if c.isspace())
dac_biet = sum(1 for c in s if not c.isalnum() and not c.isspace())
nguyen_am = sum(1 for c in s if c.isalpha() and c.lower() in 'aeiou')
phu_am = sum(1 for c in s if c.isalpha() and c.lower() not in 'aeiou')
